// Auto-generated from src/boot.ppd — do not edit manually.
// Re-generate with: ./gen_boot.sh
#ifndef BOOT_EMBEDDED_H
#define BOOT_EMBEDDED_H
#include <stdint.h>
static const char _ppd_boot_embedded[] =
  "// ── boot.ppd ──────────────────────────────────────────────────────────────────\n"
  "// Built-in module bindings for Pico-Panda programs.\n"
  "// Compiled and prepended before user code.\n"
  "//\n"
  "// Uses asm() to bridge pico-panda functions to VM CALL_MODULE instructions.\n"
  "// Args are already in locals (assembler resolves .local names to slots).\n"
  "\n"
  "// ── Signal constants ──────────────────────────────────────────────────────────\n"
  "\n"
  "const SIGNAL_SYS_START: int = 1\n"
  "const SIGNAL_APP_START: int = 2\n"
  "const SIGNAL_TICK:      int = 3\n"
  "const SIGNAL_EXIT:      int = 99\n"
  "\n"
  "// ── Console ───────────────────────────────────────────────────────────────────\n"
  "\n"
  "fun console_print_int(v: int)\n"
  "    asm(\"LOAD_LOCAL v\")\n"
  "    asm(\"CALL_MODULE CONSOLE PRINT_INT\")\n"
  "\n"
  "fun console_print_str(s: string)\n"
  "    asm(\"LOAD_LOCAL s\")\n"
  "    asm(\"CALL_MODULE CONSOLE PRINT_STR\")\n"
  "\n"
  "fun console_print_fixed(v: fixed)\n"
  "    asm(\"LOAD_LOCAL v\")\n"
  "    asm(\"CALL_MODULE CONSOLE PRINT_FIXED\")\n"
  "\n"
  "// ── Signal ────────────────────────────────────────────────────────────────────\n"
  "\n"
  "// Register a handler function address for a signal id.\n"
  "fun signal_create_handler(id: int, addr: int)\n"
  "    asm(\"LOAD_LOCAL id\")\n"
  "    asm(\"LOAD_LOCAL addr\")\n"
  "    asm(\"CALL_MODULE SIGNAL CREATE_HANDLER\")\n"
  "\n"
  "// Exit the current signal handler (task finishes).\n"
  "fun signal_handler_exit()\n"
  "    asm(\"CALL_MODULE SIGNAL EXIT_HANDLER\")\n"
  "\n"
  "// Send a signal with up to 4 register params.\n"
  "// Params are stored via STORE_REG before SEND_SIGNAL copies task.regs to signal.regs.\n"
  "fun signal_send(id: int, p0: int, p1: int, p2: int, p3: int)\n"
  "    asm(\"LOAD_LOCAL p0\")\n"
  "    asm(\"STORE_REG 0\")\n"
  "    asm(\"LOAD_LOCAL p1\")\n"
  "    asm(\"STORE_REG 1\")\n"
  "    asm(\"LOAD_LOCAL p2\")\n"
  "    asm(\"STORE_REG 2\")\n"
  "    asm(\"LOAD_LOCAL p3\")\n"
  "    asm(\"STORE_REG 3\")\n"
  "    asm(\"LOAD_LOCAL id\")\n"
  "    asm(\"CALL_MODULE SIGNAL SEND_SIGNAL\")\n"
  "\n"
  "// Exit the program: queue SIGNAL_EXIT then finish this handler.\n"
  "fun exit()\n"
  "    signal_send(SIGNAL_EXIT, 0, 0, 0, 0)\n"
  "    signal_handler_exit()\n"
  "";
static const uint32_t _ppd_boot_embedded_len =
  sizeof(_ppd_boot_embedded) - 1;
#endif // BOOT_EMBEDDED_H
